## Theory

* Scalar = 0-dimension, 1x1 Matrix
* Vector = 1-dimension
* Matrix = 2-dimension

* Addition: Must have same dimension: n1 + m1 = nm1. In programming you can add scalars to Vectors and Matrices
* Mutiplication Scalar x Vector/Matrix: The result is a vector/matrix of same length (nxm1, nxm2, nxm3)
* Multiplication Vector x Vector: Must have same length, the result is a scalar (n1xm1 + n2xm2)
* Multiplication Matrix x Matrix: The 2nd dimension of the first matrix must match the 1st dimension of the second matrix: 3,2 x 2,10 = 3,10 

Vectorized Code: Inputs matrix * Weights/Coefficients Matrix = Output matrix

* Example for the following ecuation [House Price = Coef#1 + Coef#2 x Size] :
* [House_size_matrix 1000x2] * [Correlation_matrix 2x1]= [Price_matrix 1000x1]

Image Recognition: 

* Black and white images are represented in a matrix where every element is a range from 0 to 255
* Colorful images are represented in a tensor (3 matrices for the colors red, blue and green) where every matrix has elements in a range from 0 to 255
* The np.shape(rows,columns,channels) is based on the image resolution width x height x channels
* Width = columns 
* Height = rows
* Channels = ',' for Black and white, '3' for colored images

Links 

In [1]:
import numpy as np
import os

## Display Options

In [2]:
# Eliminate Scientific Notation Method #1
"{:.2f}".format(0.00000000000007)

'0.00'

In [3]:
# Eliminate Scientific Notation Method #2
np.vectorize(lambda x:"{:.7f}".format(x))([0.00000000000007])

array(['0.0000000'], dtype='<U9')

In [4]:
# Reduce Dimensions
np.squeeze([[[[[123],[345]]]]])

array([123, 345])

# Create

## From List

In [5]:
# Can only contain 1 dtype
np.array([['30', '27', '26', '22', 28, '50', 'H'],
       ['Carol', 'Jane', 'Daniel', 'Yas', 'Kate', 'Bob', 12]])

array([['30', '27', '26', '22', '28', '50', 'H'],
       ['Carol', 'Jane', 'Daniel', 'Yas', 'Kate', 'Bob', '12']],
      dtype='<U11')

In [6]:
list_array = np.array([[1,2,3,4],[1,2,3,4]])
list_array

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## Range

In [7]:
range_12 = np.arange(12).reshape(3,4)
range_12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Random Numbers

In [8]:
np.random.rand(10) 

array([0.56932194, 0.12736396, 0.62687522, 0.23581536, 0.32654753,
       0.64904734, 0.06809576, 0.2101281 , 0.4122023 , 0.48637989])

In [4]:
random = np.random.rand(2,3,4)
random

array([[[0.39891412, 0.15460069, 0.32922418, 0.59655944],
        [0.49462022, 0.15121057, 0.79607275, 0.36038919],
        [0.74727341, 0.03648593, 0.22228198, 0.25795964]],

       [[0.6986225 , 0.71326991, 0.31124378, 0.62992426],
        [0.33484139, 0.28533448, 0.63948487, 0.73048303],
        [0.9282349 , 0.21036434, 0.26512488, 0.51947404]]])

## Zeros

In [3]:
zeros = np.zeros((2,2,2))
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

## Ones

In [11]:
ones = np.ones((2,2,2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## Specific Number

In [12]:
full_7 = np.full((2,2,2), 7)
full_7

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

# Exploratory Methods

## Get Shape

In [13]:
np.shape(np.array([[1,2,3,4,5],[6,7,8,9,10]]))    

(2, 5)

## Get Data Type

In [14]:
np.array([[1,2,3,4,5],[6,7,8,9,10]]).dtype

dtype('int32')

## Flatten Size

In [15]:
np.size(np.array([[1,2,3,4,5],[6,7,8,9,10]]))   

10

## Slicing

In [16]:
random[0][:1]

array([[0.90325694, 0.90261284, 0.76342927, 0.50434324]])

## Filtering


In [17]:
random[random > 0.5], [random > 0.5]

(array([0.90325694, 0.90261284, 0.76342927, 0.50434324, 0.68275371,
        0.9288613 , 0.78985464, 0.51243576, 0.78139682, 0.65821268,
        0.87820922, 0.69936957, 0.98859365, 0.59599624]),
 [array([[[ True,  True,  True,  True],
          [False, False,  True,  True],
          [False, False, False,  True]],
  
         [[False,  True,  True, False],
          [ True, False,  True,  True],
          [False,  True, False,  True]]])])

In [18]:
random[random >= 0.9]

array([0.90325694, 0.90261284, 0.9288613 , 0.98859365])

## Arithmetic Operations

In [19]:
list_array * list_array, np.multiply(list_array, 7)

(array([[ 1,  4,  9, 16],
        [ 1,  4,  9, 16]]),
 array([[ 7, 14, 21, 28],
        [ 7, 14, 21, 28]]))

In [20]:
list_array + list_array, np.add(list_array, list_array)

(array([[2, 4, 6, 8],
        [2, 4, 6, 8]]),
 array([[2, 4, 6, 8],
        [2, 4, 6, 8]]))

In [21]:
list_array - list_array*2, np.subtract(list_array, list_array*2)

(array([[-1, -2, -3, -4],
        [-1, -2, -3, -4]]),
 array([[-1, -2, -3, -4],
        [-1, -2, -3, -4]]))

In [22]:
list_array / list_array, np.divide(list_array, list_array*2)

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5]]))

## Summary Functions

### Min()

In [23]:
random.min()

0.05107264752040985

### Max()

In [24]:
random.max()

0.9885936541434177

### Square Root

In [25]:
np.sqrt(list_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

### Power

In [26]:
np.power(list_array,7)

array([[    1,   128,  2187, 16384],
       [    1,   128,  2187, 16384]], dtype=int32)

### Exponential

In [27]:
np.exp(list_array)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

### Logarithm

In [28]:
np.log(list_array)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [0.        , 0.69314718, 1.09861229, 1.38629436]])

### Standard Deviation

In [29]:
np.std(random)

0.2911431110588324

### Correlation

In [30]:
np.corrcoef(list_array, list_array)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Median

In [31]:
np.median(random)

0.5542159991245832

### Mean

In [32]:
np.mean(random)

0.5376394326208525

In [33]:
np.dot(list_array, list_array.reshape(4,2))

array([[22, 32],
       [22, 32]])

## Sort

In [34]:
np.sort(random)

array([[[0.50434324, 0.76342927, 0.90261284, 0.90325694],
        [0.16201638, 0.31873723, 0.68275371, 0.9288613 ],
        [0.13989931, 0.23189686, 0.32493617, 0.78985464]],

       [[0.32454389, 0.38484909, 0.51243576, 0.78139682],
        [0.28360646, 0.65821268, 0.69936957, 0.87820922],
        [0.05107265, 0.09246247, 0.59599624, 0.98859365]]])

# Update

## Convert to another dtype

In [8]:
random

array([[[0.39891412, 0.15460069, 0.32922418, 0.59655944],
        [0.49462022, 0.15121057, 0.79607275, 0.36038919],
        [0.74727341, 0.03648593, 0.22228198, 0.25795964]],

       [[0.6986225 , 0.71326991, 0.31124378, 0.62992426],
        [0.33484139, 0.28533448, 0.63948487, 0.73048303],
        [0.9282349 , 0.21036434, 0.26512488, 0.51947404]]])

In [9]:
random.astype(str)

array([[['0.3989141237648144', '0.15460068736990573',
         '0.3292241754715396', '0.5965594408998856'],
        ['0.4946202182178162', '0.15121057233137947',
         '0.7960727461339975', '0.3603891945993106'],
        ['0.7472734149223158', '0.03648592960647967',
         '0.22228197961497054', '0.2579596412096614']],

       [['0.6986225032881183', '0.7132699118795257',
         '0.31124377821070404', '0.6299242600661638'],
        ['0.33484138617114345', '0.28533447656965627',
         '0.639484874640868', '0.7304830264922644'],
        ['0.9282349033005143', '0.21036433682095212',
         '0.2651248827141859', '0.5194740380154768']]], dtype='<U32')

In [10]:
random.astype(int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

## Combine 2 Arrays

In [35]:
np.array((zeros,ones))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [36]:
np.concatenate((zeros,ones), axis=2)

array([[[0., 0., 1., 1.],
        [0., 0., 1., 1.]],

       [[0., 0., 1., 1.],
        [0., 0., 1., 1.]]])

## Reshape

In [37]:
list_array

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [38]:
list_array.reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

## Insert

In [39]:
list_array

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [40]:
np.insert(list_array, 2, [99, 100])

array([  1,   2,  99, 100,   3,   4,   1,   2,   3,   4])

In [41]:
np.append(list_array, [60,80])

array([ 1,  2,  3,  4,  1,  2,  3,  4, 60, 80])

# Delete

In [42]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [43]:
np.delete(zeros, obj=1, axis=1)

array([[[0., 0.]],

       [[0., 0.]]])

In [44]:
np.delete(zeros, obj=1, axis=0)

array([[[0., 0.],
        [0., 0.]]])

In [45]:
np.delete(zeros, obj=0, axis=2)

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

# Export

In [46]:
# Export as .npy file
np.save("3.1 - test_array", random)

# Import

## Search for File

In [47]:
# Go back one directory
# os.chdir('../')

In [48]:
# Get current working directory
os.getcwd()

'c:\\Users\\aldan\\Desktop\\Study Notes\\1 - Python General'

In [49]:
# Search the file
file = '.npy'

# Walk through the current working directory and subdirectories, returns (dirpath, [dirnames], [filenames])
for dirpath, dir_names_list, file_names_list in os.walk(os.getcwd()):
    for file_name in file_names_list:
        if file in file_name:
            path = os.path.join(dirpath, file_name)
            print (f'"{path}"')

"c:\Users\aldan\Desktop\Study Notes\1 - Python General\3.1 - test_array.npy"


## Import the File

In [50]:
# Load .npy, npz and pkl files
np.load("3.1 - test_array.npy")

array([[[0.90325694, 0.90261284, 0.76342927, 0.50434324],
        [0.31873723, 0.16201638, 0.68275371, 0.9288613 ],
        [0.13989931, 0.23189686, 0.32493617, 0.78985464]],

       [[0.32454389, 0.51243576, 0.78139682, 0.38484909],
        [0.65821268, 0.28360646, 0.87820922, 0.69936957],
        [0.09246247, 0.98859365, 0.05107265, 0.59599624]]])